"""empty message

Revision ID: 39d6c7572b9c
Revises: 64ec5023cc98
Create Date: 2023-12-16 23:10:52.732018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d6c7572b9c'
down_revision = '64ec5023cc98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
