"""Add order

Revision ID: 3e8141398423
Revises: c660c47f669e
Create Date: 2023-12-02 11:17:32.784139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e8141398423'
down_revision = 'c660c47f669e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('products_user_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('products_user_id_fkey', 'products', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_table('orders')
    # ### end Alembic commands ###
