"""empty message

Revision ID: 5788eeda7e08
Revises: 657fc534f7c4
Create Date: 2023-12-03 11:52:17.747222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5788eeda7e08'
down_revision = '657fc534f7c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
