"""empty message

Revision ID: 64ec5023cc98
Revises: ff6f97c8edbc
Create Date: 2023-12-16 22:52:27.589985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64ec5023cc98'
down_revision = 'ff6f97c8edbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
