"""fix user table

Revision ID: c660c47f669e
Revises: b102963eb7aa
Create Date: 2023-11-25 16:20:45.421424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c660c47f669e'
down_revision = 'b102963eb7aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
