"""Add create and update to Order

Revision ID: ff6f97c8edbc
Revises: 5788eeda7e08
Create Date: 2023-12-03 11:56:05.947722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff6f97c8edbc'
down_revision = '5788eeda7e08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('create', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'update')
    op.drop_column('orders', 'create')
    # ### end Alembic commands ###
